import type { PaydayRule } from "@/types";

export const PAYDAY_RULES: PaydayRule[] = [
  {
    id: "lsd",
    who: "Land and Sea Dev",
    currency: "ETB",
    freqDays: 14,
    anchor: "2026-09-18",
    received: 22000,
    save: 14500,
    keep: 7500,
    iconKey: "laptop",
    cls: "c1",
  },
  {
    id: "mmcy",
    who: "MMCY",
    currency: "ETB",
    freqMonthly: "end",
    received: 32000,
    save: 21000,
    keep: 11000,
    iconKey: "headset",
    cls: "c2",
  },
  {
    id: "sen15",
    who: "Sentrama (15th)",
    currency: "USD",
    freqMonthly: 15,
    received: 300,
    save: 300,
    keep: 0,
    iconKey: "handset",
    cls: "c3",
  },
  {
    id: "sen30",
    who: "Sentrama (30th)",
    currency: "USD",
    freqMonthly: 30,
    received: 300,
    save: 300,
    keep: 0,
    iconKey: "handset",
    cls: "c4",
  },
];
